language: php

sudo: true
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

addons:
  postgresql: "9.6"
  
services:
  - mysql
  - postgresql
  
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly
  
matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION="2.8.*@dev"
    - php: 5.6
      env: SYMFONY_VERSION="3.0.*@dev"
    - php: 7.1
      env: SYMFONY_VERSION="3.4"
      
env:
  global:
    - deps=no
    - DATABASE_NAME="my_project"
    - DATABASE_DRIVER="pdo_mysql"
    - PGUSER=postgres
    - PGDATABASE=postgres
    - SYMFONY_DEBUG="0"
    
  matrix:
    - DATABASE_DRIVER="pdo_pgsql"
    - DATABASE_DRIVER="pdo_mysql"

before_install:
  - mysql -e "CREATE DATABASE $DATABASE_NAME ;"
  - sudo service postgresql stop
  - sudo service postgresql start 9.6
  - psql -c 'create database '"$DATABASE_NAME"';' -U postgres
  - if [ "$DATABASE_DRIVER" == "pdo_pgsql" ]; then export DATABASE_PORT=5432; fi;
  - if [ "$DATABASE_DRIVER" == "pdo_pgsql" ]; then export DATABASE_USER="postgres"; fi;
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;

install:
  - if [ "$deps" = "no" ]; then composer update; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;
  - ./Tests/Resources/app/console doctrine:schema:update --force

script:
  - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml


after_script:
    - php ./vendor/bin/coveralls -v